services:
  frontend:
    image: prateekrai642/ui:0.1.1
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webappconnect
  backend:
    image: prateekrai642/nodeapp:0.1.4 
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/myDatabase"
    networks:
      - webappconnect
    restart: always
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webappconnect
    volumes:
      - studentdata:/data/db
networks:
  webappconnect: {}
volumes:
  studentdata: 
    external: true
    
